# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 369)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_tools = QtWidgets.QFrame(self.centralwidget)
        self.frame_tools.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_tools.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_tools.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tools.setObjectName("frame_tools")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_tools)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_tools)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.frame_tools)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame_tools)
        self.frame_scene = QtWidgets.QFrame(self.centralwidget)
        self.frame_scene.setMinimumSize(QtCore.QSize(300, 300))
        self.frame_scene.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_scene.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_scene.setObjectName("frame_scene")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_scene)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_scene)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.layout_scene = QtWidgets.QVBoxLayout()
        self.layout_scene.setObjectName("layout_scene")
        self.verticalLayout_3.addLayout(self.layout_scene)
        self.horizontalLayout.addWidget(self.frame_scene)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 26))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menu_file.addAction(self.action_new)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Car Sim"))
        self.label.setText(_translate("MainWindow", "Tools"))
        self.pushButton.setText(_translate("MainWindow", "Example button"))
        self.label_2.setText(_translate("MainWindow", "OpenGL context"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.action_new.setText(_translate("MainWindow", "New"))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_save_as.setText(_translate("MainWindow", "Save as.."))
        self.action_exit.setText(_translate("MainWindow", "Exit"))

